[package]
name = "serve_runtime"
version = "0.1.0"
authors = ["Kyle Phelps <kphelps@salsify.com>"]

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper", branch = "master" }
log = "0.3"
reroute = "*"
