serializer String
end

application App
    host("127.0.0.1")
    port(8080)

    serializer String
    end

    define_action(show, GET, "/")
    define_action(create, POST, "/")

    endpoint show() -> String
        return "Hello World!"
    end

    endpoint create() -> String
        return "Hello World!"
    end

end
